/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uPv2Sol from "./UPv2.sol";
export type { uPv2Sol };
export type { AdminRole } from "./AdminRole";
export type { IBEP20 } from "./IBEP20";
export type { MinterRole } from "./MinterRole";
export type { OwnerRole } from "./OwnerRole";
export type { UPv2New } from "./UPv2New";
export type { UnifiProtocolTokens } from "./UnifiProtocolTokens";
