/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBEP20__factory } from "./IBEP20__factory";
export { MinterRole__factory } from "./MinterRole__factory";
export { OwnerRole__factory } from "./OwnerRole__factory";
export { UPv2__factory } from "./UPv2__factory";
