/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBEP20 } from "./IBEP20";
export type { IUnifiCallee } from "./IUnifiCallee";
export type { MinterRole } from "./MinterRole";
export type { OwnerRole } from "./OwnerRole";
export type { UPv2 } from "./UPv2";
