/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUnifiCallee,
  IUnifiCalleeInterface,
} from "../../UPv2.sol/IUnifiCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
    ],
    name: "unifiCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IUnifiCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IUnifiCalleeInterface {
    return new utils.Interface(_abi) as IUnifiCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUnifiCallee {
    return new Contract(address, _abi, signerOrProvider) as IUnifiCallee;
  }
}
