/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AdminRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AdminRole__factory>;
    getContractFactory(
      name: "IBEP20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBEP20__factory>;
    getContractFactory(
      name: "MinterRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinterRole__factory>;
    getContractFactory(
      name: "OwnerRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnerRole__factory>;
    getContractFactory(
      name: "UnifiProtocolTokens",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UnifiProtocolTokens__factory>;
    getContractFactory(
      name: "IBEP20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBEP20__factory>;
    getContractFactory(
      name: "IUnifiCallee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUnifiCallee__factory>;
    getContractFactory(
      name: "MinterRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinterRole__factory>;
    getContractFactory(
      name: "OwnerRole",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnerRole__factory>;
    getContractFactory(
      name: "UPv2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UPv2__factory>;

    getContractAt(
      name: "AdminRole",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AdminRole>;
    getContractAt(
      name: "IBEP20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBEP20>;
    getContractAt(
      name: "MinterRole",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MinterRole>;
    getContractAt(
      name: "OwnerRole",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnerRole>;
    getContractAt(
      name: "UnifiProtocolTokens",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UnifiProtocolTokens>;
    getContractAt(
      name: "IBEP20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBEP20>;
    getContractAt(
      name: "IUnifiCallee",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUnifiCallee>;
    getContractAt(
      name: "MinterRole",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MinterRole>;
    getContractAt(
      name: "OwnerRole",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnerRole>;
    getContractAt(
      name: "UPv2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UPv2>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
