/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uPv2Sol from "./UPv2.sol";
export type { uPv2Sol };
export type { AdminRole } from "./AdminRole";
export type { IBEP20 } from "./IBEP20";
export type { MinterRole } from "./MinterRole";
export type { OwnerRole } from "./OwnerRole";
export type { UnifiProtocolTokens } from "./UnifiProtocolTokens";
export * as factories from "./factories";
export { AdminRole__factory } from "./factories/AdminRole__factory";
export { IBEP20__factory } from "./factories/IBEP20__factory";
export { MinterRole__factory } from "./factories/MinterRole__factory";
export { OwnerRole__factory } from "./factories/OwnerRole__factory";
export { UnifiProtocolTokens__factory } from "./factories/UnifiProtocolTokens__factory";
export type { IUnifiCallee } from "./UPv2.sol/IUnifiCallee";
export { IUnifiCallee__factory } from "./factories/UPv2.sol/IUnifiCallee__factory";
export type { UPv2 } from "./UPv2.sol/UPv2";
export { UPv2__factory } from "./factories/UPv2.sol/UPv2__factory";
